# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := All
### Rules for final target.
$(obj).target/All.stamp: TOOLSET := $(TOOLSET)
$(obj).target/All.stamp: $(obj).target/talk/libjingle.a $(obj).target/talk/libjingle_p2p.a FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/All.stamp
# Add target alias
.PHONY: All
All: $(obj).target/All.stamp

# Add target alias to "all" target.
.PHONY: all
all: All

